### ISSUE TITLE
Not push production docker image when dev branch updates, and remove dispatch trigger

### ISSUE THREAD

**Issue by Nictheboy** [SageSeekerSociety/cheese-backend#105]
```yml
on: 
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
```
However, why we need to update prod image when dev is updated?
(Maybe this is written like this to test the workflow file, but we should remove '- dev' some day)
